[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install --include=dev && npm run build"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
